"use strict";

/** @type {import('sequelize-cli').Migration} */
module.exports = {
    async up(queryInterface, Sequelize) {
        await queryInterface.bulkInsert(
            "sales",
           
 [
    { 
        id:1001,
        year: 2014,  
        product_id: 101,
        sale_amount: 283567,
        country_id: 1,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1002,
        year: 2014,  
        product_id: 102,
        sale_amount: 901393,
        country_id: 1,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1003,
        year: 2014,   
        product_id: 103,
        sale_amount: 18628,
        country_id: 1,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1004,
        year: 2014,   
        product_id: 104,
        sale_amount: 139404,
        country_id: 1,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1005,
        year: 2014,   
         product_id: 105,
        sale_amount: 0,
        country_id: 1,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1006,
        year: 2014,  
          product_id: 106,
        sale_amount: 0,
        country_id: 1,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1007,
        year: 2014,  
          product_id: 107,
        sale_amount: 258299,
        country_id: 1,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1008,
        year: 2014,   
         product_id: 108,
        sale_amount: 0,
        country_id: 1,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1009,
        year: 2014,   
         product_id: 101,
        sale_amount: 183567,
        country_id: 2,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1010,
        year: 2014, 
           product_id: 102,
        sale_amount: 201393,
        country_id: 2,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1011,
        year: 2014,
            product_id: 103,
        sale_amount: 38628,
        country_id: 2,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1012,
        year: 2014, 
           product_id: 104,
        sale_amount: 0,
        country_id: 2,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1013,
        year: 2014, 
           product_id: 105,
        sale_amount: 144677,
        country_id: 2,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1014,
        year: 2014,
            product_id: 106,
        sale_amount: 443673,
        country_id: 2,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1015,
        year: 2014,  
          product_id: 107,
        sale_amount: 0,
        country_id: 2,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1016,
        year: 2014,   
         product_id: 108,
        sale_amount: 0,
        country_id: 2,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1017,
        year: 2014, 
           product_id: 101,
        sale_amount: 483567,
        country_id: 3,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1018,
        year: 2014, 
           product_id: 102,
        sale_amount: 101393,
        country_id: 3,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1019,
        year: 2014,
            product_id: 103,
        sale_amount: 0,
        country_id: 3,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1020,
        year: 2014,
            product_id: 104,
        sale_amount: 12628,
        country_id: 3,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1021,
        year: 2014, 
           product_id: 105,
        sale_amount: 144657,
        country_id: 3,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:198,
        year: 2014, 
           product_id: 106,
        sale_amount: 0,
        country_id: 3,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:199,
        year: 2014,
            product_id: 107,
        sale_amount: 143273,
        country_id: 3,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1022,
        year: 2014,
            product_id: 108,
        sale_amount: 0,
        country_id: 3,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1023,
        year: 2014,
            product_id: 101,
        sale_amount: 0,
        country_id: 4,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1024,
        year: 2014,
            product_id: 102,
        sale_amount: 151393,
        country_id: 4,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1025,
        year: 2014,
            product_id: 103,
        sale_amount: 454393,
        country_id: 4,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1026,
        year: 2014, 
           product_id: 104,
        sale_amount: 32628,
        country_id: 4,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1027,
        year: 2014,
            product_id: 105,
        sale_amount: 0,
        country_id: 4,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1028,
        year: 2014, 
           product_id: 106,
        sale_amount: 0,
        country_id: 4,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1029,
        year: 2014, 
           product_id: 107,
        sale_amount: 0,
        country_id: 4,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1030,
        year: 2014,
            product_id: 108,
        sale_amount: 401394,
        country_id: 4,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1031,
        year: 2013,
        product_id: 101,
        sale_amount: 123562,
        country_id: 1,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1032,
        year: 2013,
        product_id: 102,
        sale_amount: 701393,
        country_id: 1,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1033,
        year: 2013,
        product_id: 103,
        sale_amount: 28628,
        country_id: 1,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1034,
        year: 2013,
        product_id: 104,
        sale_amount: 239404,
        country_id: 1,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1035,
        year: 2013,
        product_id: 105,
        sale_amount: 1000,
        country_id: 1,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1036,
        year: 2013,
        product_id: 106,
        sale_amount: 0,
        country_id: 1,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1037,
        year: 2013,
        product_id: 107,
        sale_amount: 158299,
        country_id: 1,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1038,
        year: 2013,
        product_id: 108,
        sale_amount: 0,
        country_id: 1,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1039,
        year: 2013,
        product_id: 101,
        sale_amount: 0,
        country_id: 2,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1040,
        year: 2013,
        product_id: 102,
        sale_amount: 401493,
        country_id: 2,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1041,
        year: 2013,
        product_id: 103,
        sale_amount: 0,
        country_id: 2,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1042,
        year: 2013,
        product_id: 104,
        sale_amount: 28614,
        country_id: 2,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1043,
        year: 2013,
        product_id: 105,
        sale_amount: 184677,
        country_id: 2,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1044,
        year: 2013,
        product_id: 106,
        sale_amount: 243673,
        country_id: 2,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1045,
        year: 2013,
        product_id: 107,
        sale_amount: 0,
        country_id: 2,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1046,
        year: 2013,
        product_id: 108,
        sale_amount: 12347,
        country_id: 2,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1047,
        year: 2013,
        product_id: 101,
        sale_amount: 0,
        country_id: 3,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1048,
        year: 2013,
        product_id: 102,
        sale_amount: 201493,
        country_id: 3,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1049,
        year: 2013,
        product_id: 103,
        sale_amount: 0,
        country_id: 3,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1050,
        year: 2013,
        product_id: 104,
        sale_amount: 12658,
        country_id: 3,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1051,
        year: 2013,
        product_id: 105,
        sale_amount: 0,
        country_id: 3,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1052,
        year: 2013,
        product_id: 106,
        sale_amount: 45623,
        country_id: 3,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1053,
        year: 2013,
        product_id: 107,
        sale_amount: 243273,
        country_id: 3,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1054,
        year: 2013,
        product_id: 108,
        sale_amount: 0,
        country_id: 3,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1055,
        year: 2013,
        product_id: 101,
        sale_amount: 65321,
        country_id: 4,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1056,
        year: 2013,
        product_id: 102,
        sale_amount: 251393,
        country_id: 4,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1057,
        year: 2013,
        product_id: 103,
        sale_amount: 354393,
        country_id: 4,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1058,
        year: 2013,
        product_id: 104,
        sale_amount: 52628,
        country_id: 4,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1059,
        year: 2013,
        product_id: 105,
        sale_amount: 23415,
        country_id: 4,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1060,
        year: 2013,
        product_id: 106,
        sale_amount: 0,
        country_id: 4,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1061,
        year: 2013,
        product_id: 107,
        sale_amount: 0,
        country_id: 4,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1062,
        year: 2013,
        product_id: 108,
        sale_amount: 101394,
        country_id: 4,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1063,
        year: 2012,
        product_id: 101,
        sale_amount: 13562,
        country_id: 1,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1064,
        year: 2012,
        product_id: 102,
        sale_amount: 201393,
        country_id: 1,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1065,
        year: 2012,
        product_id: 103,
        sale_amount: 128628,
        country_id: 1,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1066,
        year: 2012,
        product_id: 104,
        sale_amount: 439404,
        country_id: 1,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1067,
        year: 2012,
        product_id: 105,
        sale_amount: 101230,
        country_id: 1,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1068,
        year: 2012,
        product_id: 106,
        sale_amount: 0,
        country_id: 1,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1069,
        year: 2012,
        product_id: 107,
        sale_amount: 0,
        country_id: 1,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1070,
        year: 2012,
        product_id: 108,
        sale_amount: 41244,
        country_id: 1,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1071,
        year: 2012,
        product_id: 101,
        sale_amount: 53214,
        country_id: 2,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1072,
        year: 2012,
        product_id: 102,
        sale_amount: 101493,
        country_id: 2,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1073,
        year: 2012,
        product_id: 103,
        sale_amount: 76523,
        country_id: 2,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1074,
        year: 2012,
        product_id: 104,
        sale_amount: 0,
        country_id: 2,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1075,
        year: 2012,
        product_id: 105,
        sale_amount: 384677,
        country_id: 2,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1076,
        year: 2012,
        product_id: 106,
        sale_amount: 143673,
        country_id: 2,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1077,
        year: 2012,
        product_id: 107,
        sale_amount: 0,
        country_id: 2,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1078,
        year: 2012,
        product_id: 108,
        sale_amount: 132347,
        country_id: 2,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1079,
        year: 2012,
        product_id: 101,
        sale_amount: 13478,
        country_id: 3,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1080,
        year: 2012,
        product_id: 102,
        sale_amount: 10873,
        country_id: 3,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1081,
        year: 2012,
        product_id: 103,
        sale_amount: 0,
        country_id: 3,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1082,
        year: 2012,
        product_id: 104,
        sale_amount: 0,
        country_id: 3,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1083,
        year: 2012,
        product_id: 105,
        sale_amount: 53134,
        country_id: 3,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1084,
        year: 2012,
        product_id: 106,
        sale_amount: 45627,
        country_id: 3,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1085,
        year: 2012,
        product_id: 107,
        sale_amount: 0,
        country_id: 3,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1086,
        year: 2012,
        product_id: 108,
        sale_amount: 23273,
        country_id: 3,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1087,
        year: 2012,
        product_id: 101,
        sale_amount: 35321,
        country_id: 4,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1088,
        year: 2012,
        product_id: 102,
        sale_amount: 151393,
        country_id: 4,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1089,
        year: 2012,
        product_id: 103,
        sale_amount: 454393,
        country_id: 4,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1090,
        year: 2012,
        product_id: 104,
        sale_amount: 0,
        country_id: 4,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1091,
        year: 2012,
        product_id: 105,
        sale_amount: 13415,
        country_id: 4,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1092,
        year: 2012,
        product_id: 106,
        sale_amount: 44312,
        country_id: 4,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1093,
        year: 2012,
        product_id: 107,
        sale_amount: 0,
        country_id: 4,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1094,
        year: 2012,
        product_id: 108,
        sale_amount: 0,
        country_id: 4,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1095,
        year: 2011,
        product_id: 101,
        sale_amount: 13782,
        country_id: 1,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1096,
        year: 2011,
        product_id: 102,
        sale_amount: 207823,
        country_id: 1,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1097,
        year: 2011,
        product_id: 103,
        sale_amount: 127828,
        country_id: 1,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1098,
        year: 2011,
        product_id: 104,
        sale_amount: 437824,
        country_id: 1,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1099,
        year: 2011,
        product_id: 105,
        sale_amount: 107820,
        country_id: 1,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1100,
        year: 2011,
        product_id: 106,
        sale_amount: 0,
        country_id: 1,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1101,
        year: 2011,
        product_id: 107,
        sale_amount: 18233,
        country_id: 1,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1102,
        year: 2011,
        product_id: 108,
        sale_amount: 41782,
        country_id: 1,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1103,
        year: 2011,
        product_id: 101,
        sale_amount: 53782,
        country_id: 2,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1104,
        year: 2011,
        product_id: 102,
        sale_amount: 107823,
        country_id: 2,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1105,
        year: 2011,
        product_id: 103,
        sale_amount: 0,
        country_id: 2,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:197,
        year: 2011,
        product_id: 104,
        sale_amount: 36782,
        country_id: 2,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1106,
        year: 2011,
        product_id: 105,
        sale_amount: 187827,
        country_id: 2,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1107,
        year: 2011,
        product_id: 106,
        sale_amount: 147823,
        country_id: 2,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1108,
        year: 2011,
        product_id: 107,
        sale_amount: 0,
        country_id: 2,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1109,
        year: 2011,
        product_id: 108,
        sale_amount: 137827,
        country_id: 2,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1110,
        year: 2011,
        product_id: 101,
        sale_amount: 13782,
        country_id: 3,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1111,
        year: 2011,
        product_id: 102,
        sale_amount: 10782,
        country_id: 3,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1112,
        year: 2011,
        product_id: 103,
        sale_amount: 0,
        country_id: 3,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1113,
        year: 2011,
        product_id: 104,
        sale_amount: 78233,
        country_id: 3,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1114,
        year: 2011,
        product_id: 105,
        sale_amount: 53782,
        country_id: 3,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1115,
        year: 2011,
        product_id: 106,
        sale_amount: 45782,
        country_id: 3,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1116,
        year: 2011,
        product_id: 107,
        sale_amount: 0,
        country_id: 3,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1117,
        year: 2011,
        product_id: 108,
        sale_amount: 23782,
        country_id: 3,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1118,
        year: 2011,
        product_id: 101,
        sale_amount: 35782,
        country_id: 4,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1119,
        year: 2011,
        product_id: 102,
        sale_amount: 157823,
        country_id: 4,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1120,
        year: 2011,
        product_id: 103,
        sale_amount: 457823,
        country_id: 4,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1121,
        year: 2011,
        product_id: 104,
        sale_amount: 0,
        country_id: 4,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1122,
        year: 2011,
        product_id: 105,
        sale_amount: 13782,
        country_id: 4,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1123,
        year: 2011,
        product_id: 106,
        sale_amount: 44782,
        country_id: 4,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1124,
        year: 2011,
        product_id: 107,
        sale_amount: 18245,
        country_id: 4,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1125,
        year: 2011,
        product_id: 108,
        sale_amount: 0,
        country_id: 4,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1126,
        year: 2010,
        product_id: 101,
        sale_amount: 32642,
        country_id: 1,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1127,
        year: 2010,
        product_id: 102,
        sale_amount: 23642,
        country_id: 1,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1128,
        year: 2010,
        product_id: 103,
        sale_amount: 128642,
        country_id: 1,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1129,
        year: 2010,
        product_id: 104,
        sale_amount: 478242,
        country_id: 1,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1130,
        year: 2010,
        product_id: 105,
        sale_amount: 178264,
        country_id: 1,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1131,
        year: 2010,
        product_id: 106,
        sale_amount: 49876,
        country_id: 1,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1132,
        year: 2010,
        product_id: 107,
        sale_amount: 823642,
        country_id: 1,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1133,
        year: 2010,
        product_id: 108,
        sale_amount: 0,
        country_id: 1,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1134,
        year: 2010,
        product_id: 101,
        sale_amount: 537826,
        country_id: 2,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1135,
        year: 2010,
        product_id: 102,
        sale_amount: 0,
        country_id: 2,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1136,
        year: 2010,
        product_id: 103,
        sale_amount: 32642,
        country_id: 2,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1137,
        year: 2010,
        product_id: 104,
        sale_amount: 656422,
        country_id: 2,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1138,
        year: 2010,
        product_id: 105,
        sale_amount: 72764,
        country_id: 2,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1139,
        year: 2010,
        product_id: 106,
        sale_amount: 0,
        country_id: 2,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1140,
        year: 2010,
        product_id: 107,
        sale_amount: 82423,
        country_id: 2,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1141,
        year: 2010,
        product_id: 108,
        sale_amount: 137852,
        country_id: 2,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1142,
        year: 2010,
        product_id: 101,
        sale_amount: 444123,
        country_id: 3,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1143,
        year: 2010,
        product_id: 102,
        sale_amount: 0,
        country_id: 3,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1144,
        year: 2010,
        product_id: 103,
        sale_amount: 23673,
        country_id: 3,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1145,
        year: 2010,
        product_id: 104,
        sale_amount: 0,
        country_id: 3,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1146,
        year: 2010,
        product_id: 105,
        sale_amount: 782642,
        country_id: 3,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1147,
        year: 2010,
        product_id: 106,
        sale_amount: 452642,
        country_id: 3,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1148,
        year: 2010,
        product_id: 107,
        sale_amount: 12354,
        country_id: 3,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1149,
        year: 2010,
        product_id: 108,
        sale_amount: 232642,
        country_id: 3,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1150,
        year: 2010,
        product_id: 101,
        sale_amount: 178242,
        country_id: 4,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1151,
        year: 2010,
        product_id: 102,
        sale_amount: 33642,
        country_id: 4,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1152,
        year: 2010,
        product_id: 103,
        sale_amount: 823642,
        country_id: 4,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1153,
        year: 2010,
        product_id: 104,
        sale_amount: 76523,
        country_id: 4,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1154,
        year: 2010,
        product_id: 105,
        sale_amount: 132642,
        country_id: 4,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1155,
        year: 2010,
        product_id: 106,
        sale_amount: 782642,
        country_id: 4,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1156,
        year: 2010,
        product_id: 107,
        sale_amount: 246424,
        country_id: 4,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1157,
        year: 2010,
        product_id: 108,
        sale_amount: 123127,
        country_id: 4,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1158,
        year: 2009,
        product_id: 101,
        sale_amount: 132424,
        country_id: 1,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1159,
        year: 2009,
        product_id: 102,
        sale_amount: 223424,
        country_id: 1,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1160,
        year: 2009,
        product_id: 103,
        sale_amount: 128424,
        country_id: 1,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1161,
        year: 2009,
        product_id: 104,
        sale_amount: 43724,
        country_id: 1,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1162,
        year: 2009,
        product_id: 105,
        sale_amount: 53123,
        country_id: 1,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1163,
        year: 2009,
        product_id: 106,
        sale_amount: 455524,
        country_id: 1,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1164,
        year: 2009,
        product_id: 107,
        sale_amount: 20024,
        country_id: 1,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1165,
        year: 2009,
        product_id: 108,
        sale_amount: 71424,
        country_id: 1,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1166,
        year: 2009,
        product_id: 101,
        sale_amount: 57424,
        country_id: 2,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1167,
        year: 2009,
        product_id: 102,
        sale_amount: 61424,
        country_id: 2,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1168,
        year: 2009,
        product_id: 103,
        sale_amount: 32424,
        country_id: 2,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1169,
        year: 2009,
        product_id: 104,
        sale_amount: 654242,
        country_id: 2,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1170,
        year: 2009,
        product_id: 105,
        sale_amount: 727427,
        country_id: 2,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1171,
        year: 2009,
        product_id: 106,
        sale_amount: 237812,
        country_id: 2,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1172,
        year: 2009,
        product_id: 107,
        sale_amount: 84243,
        country_id: 2,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1173,
        year: 2009,
        product_id: 108,
        sale_amount: 137024,
        country_id: 2,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1174,
        year: 2009,
        product_id: 101,
        sale_amount: 76123,
        country_id: 3,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1175,
        year: 2009,
        product_id: 102,
        sale_amount: 51008,
        country_id: 3,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1176,
        year: 2009,
        product_id: 103,
        sale_amount: 32424,
        country_id: 3,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1177,
        year: 2009,
        product_id: 104,
        sale_amount: 214249,
        country_id: 3,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1178,
        year: 2009,
        product_id: 105,
        sale_amount: 782424,
        country_id: 3,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1179,
        year: 2009,
        product_id: 106,
        sale_amount: 465424,
        country_id: 3,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1180,
        year: 2009,
        product_id: 107,
        sale_amount: 237865,
        country_id: 3,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1181,
        year: 2009,
        product_id: 108,
        sale_amount: 232424,
        country_id: 3,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1182,
        year: 2009,
        product_id: 101,
        sale_amount: 57844,
        country_id: 4,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1183,
        year: 2009,
        product_id: 102,
        sale_amount: 33424,
        country_id: 4,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1184,
        year: 2009,
        product_id: 103,
        sale_amount: 823424,
        country_id: 4,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1185,
        year: 2009,
        product_id: 104,
        sale_amount: 314246,
        country_id: 4,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1186,
        year: 2009,
        product_id: 105,
        sale_amount: 402024,
        country_id: 4,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1187,
        year: 2009,
        product_id: 106,
        sale_amount: 282424,
        country_id: 4,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1188,
        year: 2009,
        product_id: 107,
        sale_amount: 98123,
        country_id: 4,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1189,
        year: 2009,
        product_id: 108,
        sale_amount: 63424,
        country_id: 4,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1190,
        year: 2008,
        product_id: 101,
        sale_amount: 169474,
        country_id: 1,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1191,
        year: 2008,
        product_id: 102,
        sale_amount: 103724,
        country_id: 1,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1192,
        year: 2008,
        product_id: 103,
        sale_amount: 298724,
        country_id: 1,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1193,
        year: 2008,
        product_id: 104,
        sale_amount: 871234,
        country_id: 1,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1194,
        year: 2008,
        product_id: 105,
        sale_amount: 42356,
        country_id: 1,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1195,
        year: 2008,
        product_id: 106,
        sale_amount: 129574,
        country_id: 1,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1196,
        year: 2008,
        product_id: 107,
        sale_amount: 19474,
        country_id: 1,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1197,
        year: 2008,
        product_id: 108,
        sale_amount: 121927,
        country_id: 1,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1198,
        year: 2008,
        product_id: 101,
        sale_amount: 31145,
        country_id: 2,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1199,
        year: 2008,
        product_id: 102,
        sale_amount: 33213,
        country_id: 2,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1200,
        year: 2008,
        product_id: 103,
        sale_amount: 51209,
        country_id: 2,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1201,
        year: 2008,
        product_id: 104,
        sale_amount: 15922,
        country_id: 2,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1202,
        year: 2008,
        product_id: 105,
        sale_amount: 329474,
        country_id: 2,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1203,
        year: 2008,
        product_id: 106,
        sale_amount: 12355,
        country_id: 2,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1204,
        year: 2008,
        product_id: 107,
        sale_amount: 139872,
        country_id: 2,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1205,
        year: 2008,
        product_id: 108,
        sale_amount: 76123,
        country_id: 2,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1206,
        year: 2008,
        product_id: 101,
        sale_amount: 600189,
        country_id: 3,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1207,
        year: 2008,
        product_id: 102,
        sale_amount: 213927,
        country_id: 3,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1208,
        year: 2008,
        product_id: 103,
        sale_amount: 119273,
        country_id: 3,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1209,
        year: 2008,
        product_id: 104,
        sale_amount: 123673,
        country_id: 3,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1210,
        year: 2008,
        product_id: 105,
        sale_amount: 159474,
        country_id: 3,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1211,
        year: 2008,
        product_id: 106,
        sale_amount: 342927,
        country_id: 3,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1212,
        year: 2008,
        product_id: 107,
        sale_amount: 125270,
        country_id: 3,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1213,
        year: 2008,
        product_id: 108,
        sale_amount: 130474,
        country_id: 3,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1214,
        year: 2008,
        product_id: 101,
        sale_amount: 12375,
        country_id: 4,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1215,
        year: 2008,
        product_id: 102,
        sale_amount: 243927,
        country_id: 4,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1216,
        year: 2008,
        product_id: 103,
        sale_amount: 332944,
        country_id: 4,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1217,
        year: 2008,
        product_id: 104,
        sale_amount: 49087,
        country_id: 4,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1218,
        year: 2008,
        product_id: 105,
        sale_amount: 139474,
        country_id: 4,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1219,
        year: 2008,
        product_id: 106,
        sale_amount: 189474,
        country_id: 4,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1220,
        year: 2008,
        product_id: 107,
        sale_amount: 17809,
        country_id: 4,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1221,
        year: 2008,
        product_id: 108,
        sale_amount: 129474,
        country_id: 4,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1222,
        year: 2007,
        product_id: 101,
        sale_amount: 94732,
        country_id: 1,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1223,
        year: 2007,
        product_id: 102,
        sale_amount: 27232,
        country_id: 1,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1224,
        year: 2007,
        product_id: 103,
        sale_amount: 987232,
        country_id: 1,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1225,
        year: 2007,
        product_id: 104,
        sale_amount: 123356,
        country_id: 1,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1226,
        year: 2007,
        product_id: 105,
        sale_amount: 0,
        country_id: 1,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1227,
        year: 2007,
        product_id: 106,
        sale_amount: 95732,
        country_id: 1,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1228,
        year: 2007,
        product_id: 107,
        sale_amount: 84732,
        country_id: 1,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1229,
        year: 2007,
        product_id: 108,
        sale_amount: 0,
        country_id: 1,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1230,
        year: 2007,
        product_id: 101,
        sale_amount: 43122,
        country_id: 2,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1231,
        year: 2007,
        product_id: 102,
        sale_amount: 12132,
        country_id: 2,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1232,
        year: 2007,
        product_id: 103,
        sale_amount: 0,
        country_id: 2,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1233,
        year: 2007,
        product_id: 104,
        sale_amount: 59232,
        country_id: 2,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1234,
        year: 2007,
        product_id: 105,
        sale_amount: 29472,
        country_id: 2,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1235,
        year: 2007,
        product_id: 106,
        sale_amount: 43187,
        country_id: 2,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1236,
        year: 2007,
        product_id: 107,
        sale_amount: 0,
        country_id: 2,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1237,
        year: 2007,
        product_id: 108,
        sale_amount: 3612,
        country_id: 2,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1238,
        year: 2007,
        product_id: 101,
        sale_amount: 0,
        country_id: 3,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1239,
        year: 2007,
        product_id: 102,
        sale_amount: 13922,
        country_id: 3,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1240,
        year: 2007,
        product_id: 103,
        sale_amount: 92701,
        country_id: 3,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1241,
        year: 2007,
        product_id: 104,
        sale_amount: 0,
        country_id: 3,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1242,
        year: 2007,
        product_id: 105,
        sale_amount: 294732,
        country_id: 3,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1243,
        year: 2007,
        product_id: 106,
        sale_amount: 129232,
        country_id: 3,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1244,
        year: 2007,
        product_id: 107,
        sale_amount: 527032,
        country_id: 3,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1245,
        year: 2007,
        product_id: 108,
        sale_amount: 0,
        country_id: 3,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1246,
        year: 2007,
        product_id: 101,
        sale_amount: 22232,
        country_id: 4,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1247,
        year: 2007,
        product_id: 102,
        sale_amount: 9232,
        country_id: 4,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1248,
        year: 2007,
        product_id: 103,
        sale_amount: 9432,
        country_id: 4,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1249,
        year: 2007,
        product_id: 104,
        sale_amount: 0,
        country_id: 4,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1250,
        year: 2007,
        product_id: 105,
        sale_amount: 294732,
        country_id: 4,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1251,
        year: 2007,
        product_id: 106,
        sale_amount: 194732,
        country_id: 4,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1252,
        year: 2007,
        product_id: 107,
        sale_amount: 29473,
        country_id: 4,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id:1253,
        year: 2007,
        product_id: 108,
        sale_amount: 0,
        country_id: 4,
        created_at: new Date(),
        updated_at: new Date(),
    }
    ],
            {}
        );
    },

    async down(queryInterface, Sequelize) {
        await queryInterface.bulkDelete("sales", null, {});
    },
};
